name: notecraft
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  date_format: ^2.0.7
  drift: ^2.14.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.6
  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  sqlite3_flutter_libs: ^0.5.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.7
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/no_notes.png
    - assets/images/empty_trash.png
    - assets/images/favorite_note.png
    - assets/images/logo.png

flutter_native_splash:
  image: "assets/images/logo.png"
  color: "#000000"
  android_12:
    image: "assets/images/logo.png"
